version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: username2478/ac2_ca
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
    ports:
      - "8686:8686"
    depends_on:
      - database
volumes:
  db-volume: